require(sqldf)
require(data.table)
require(dplyr)
setwd("~/GitHub/ExData_Plotting1/data")
data <- tbl_df(read.csv.sql("household_power_consumption.txt", sql="select * from file where Date = '2/2/2007' or Date = '1/2/2007'", header=TRUE, sep=";"))
closeAllConnections()
globalActivePower <- as.numeric(data$Global_active_power)
png("../plot1.png", width=480, height=480)
hist(globalActivePower, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()